export const FETCH_WEATHER_REPORT_REQUEST = 'FETCH_WEATHER_REPORT_REQUEST';
export const FETCH_WEATHER_REPORT_SUCCESS = 'FETCH_WEATHER_REPORT_SUCCESS';
export const FETCH_WEATHER_REPORT_FAILURE  = 'FETCH_WEATHER_REPORT_FAILURE';
